twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['tailwind_2_layout.html.twig']
    globals:
        project_name: '%env(PROJECT_NAME)%'

when@test:
    twig:
        strict_variables: true
