twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['tailwind_2_layout.html.twig']
    globals:
        project_name: '%env(PROJECT_NAME)%'
        new_exercises_days_offset: '%env(NEW_EXERCISES_DAYS_OFFSET)%'
        allCourses: '@App\Twig\Extension\CourseExtension'

when@test:
    twig:
        strict_variables: true
