vich_uploader:
    db_driver: orm

    mappings:
       file:
           uri_prefix: /images/file
           upload_destination: '%kernel.project_dir%/public/images/file'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           delete_on_update: true
           delete_on_remove: true
